import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      zIndex: {
        content: "0",
        sticky: "10",
        bottomNav: "20",
        header: "30",
        devTools: "40",
        backdrop: "50",
        drawer: "60",
        modal: "70",
        toast: "80",
      },
      colors: {
        fest: {
          cream: "var(--background)",
          parchment: "var(--surface-muted)",
          linen: "#FFF7ED",
          surface: "var(--surface)",
          surfaceMuted: "var(--surface-muted)",
          border: "var(--border)",
          borderDark: "var(--border-strong)",
          charcoal: "var(--text-primary)",
          charcoalMuted: "var(--text-secondary)",
          charcoalTertiary: "var(--text-tertiary)",
          terracotta: "#FF5722",
          terracottaDark: "#E64A19",
          terracottaLight: "rgba(255, 87, 34, 0.12)",
          saffron: "#F59E0B",
          saffronDark: "#D97706",
          saffronLight: "rgba(245, 158, 11, 0.12)",
          turmeric: "#FBBF24",
          cardamom: "#10B981",
          cardamomLight: "rgba(16, 185, 129, 0.12)",
          ember: "#EA580C",
          gold: "#F59E0B",
          goldLight: "rgba(245, 158, 11, 0.12)",
          orange: "#FF5722",
          orangeLight: "rgba(255, 87, 34, 0.12)",
          green: "#10B981",
          greenLight: "rgba(16, 185, 129, 0.12)",
          red: "#EF4444",
          // Clean surfaces for orange & white theme
          card: "#FFFFFF",
          cardHover: "#FFFBF5",
          cardDark: "#FFFFFF",
          cardHoverDark: "#FFFBF5",
          borderDarkTheme: "#E2E8F0",
          textDarkTheme: "#0F172A",
          textDarkMuted: "#64748B",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Plus Jakarta Sans", "Inter", "-apple-system", "sans-serif"],
        display: ["var(--font-display)", "Outfit", "Plus Jakarta Sans", "Inter", "sans-serif"],
        serif: ["var(--font-serif)", "Playfair Display", "Georgia", "serif"],
      },
      boxShadow: {
        subtle: "0 1px 2px 0 rgba(26, 22, 20, 0.04)",
        medium: "0 4px 12px -2px rgba(26, 22, 20, 0.08)",
        card: "0 2px 8px -2px rgba(26, 22, 20, 0.06), 0 1px 3px -1px rgba(26, 22, 20, 0.04)",
        stamp: "0 2px 0 0 rgba(180, 83, 9, 0.2)",
        ticket: "0 8px 24px -4px rgba(224, 83, 38, 0.12), 0 2px 6px -1px rgba(26, 22, 20, 0.06)",
        warm: "0 10px 30px -5px rgba(217, 119, 6, 0.15)",
        overlay: "0 20px 25px -5px rgba(0, 0, 0, 0.25)",
        drawer: "0 25px 50px -12px rgba(0, 0, 0, 0.4)",
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        card: "14px",
        cardLg: "20px",
      },
    },
  },
  plugins: [],
};

export default config;
